### ISSUE TITLE
TypeError: super() takes at least 1 argument (0 given)

### ISSUE THREAD

**Issue by keishatsai** [windowsub0406/KITTI_Tutorial#3]
Hi, 
Thanks for the tutorial.
Here is what I have encountered when I run the code which you provided "[Project 3D Velodyne points to 2D camera Image](https://github.com/windowsub0406/KITTI_Tutorial/blob/master/velo2cam_projection.ipynb) ", I got error message.
I put the code you provided in ipython notebook inside one file called, "projectVelo.py", and I only changed the path to velodyne and image file.

Traceback (most recent call last):
  File "projectVelo.py", line 54, in <module>
    res = Kitti_util(frame=128, camera_path=image_path, velo_path=velo_path, v2c_path=v2c_filepath, c2c_path=c2c_filepath)
  File "/home/keisha_tsai/Downloads/KITTI_Tutorial-master/kitti_foundation.py", line 235, in __init__
    super().__init__(frame, velo_path, camera_path, img_type, v2c_path, c2c_path, xml_path)
TypeError: super() takes at least 1 argument (0 given)

Could you help me to clarify the error? Thank you.

**Comment by keishatsai** [comment]
Maybe it is because of the version of python.
so I changed the the line 235 into
Kitti.__init__(self,frame, velo_path, camera_path, img_type, v2c_path, c2c_path, xml_path)
now it works for me....
