### ISSUE TITLE
TypeError: 'generator' object has no attribute '__getitem__'

### ISSUE THREAD

**Issue by keishatsai** [windowsub0406/KITTI_Tutorial#4]
Hi, 
Here is what I have encountered when I run the code which you provided "[Project 3D Velodyne points to 2D camera Image](https://github.com/windowsub0406/KITTI_Tutorial/blob/master/velo2cam_projection.ipynb) ", I got error message.
I put the code you provided in ipython notebook inside one file called, "projectVelo.py", and I only changed the path to velodyne and image file.

Here is the error message:

Traceback (most recent call last):
  File "projectVelo.py", line 60, in <module>
    img, pnt, c_ = res.velo_projection_frame(v_fov=v_fov, h_fov=h_fov)
  File "/home/keisha_tsai/Downloads/KITTI_Tutorial-master/kitti_foundation.py", line 611, in velo_projection_frame
    res, c_ = self.__velo_2_img_projection(velo_gen)
  File "/home/keisha_tsai/Downloads/KITTI_Tutorial-master/kitti_foundation.py", line 486, in __velo_2_img_projection
    xyz_v, c_ = self.__point_matrix(points)
  File "/home/keisha_tsai/Downloads/KITTI_Tutorial-master/kitti_foundation.py", line 305, in __point_matrix
    self.__points_filter(points)
  File "/home/keisha_tsai/Downloads/KITTI_Tutorial-master/kitti_foundation.py", line 368, in __points_filter
    self.__upload_points(points)
  File "/home/keisha_tsai/Downloads/KITTI_Tutorial-master/kitti_foundation.py", line 296, in __upload_points
    self.__x = points[:, 0]
TypeError: 'generator' object has no attribute '__getitem__'

Hope anyone can help me to solve this problem.
Thank you.

**Comment by keishatsai** [comment]
The problem didn't occur when I used the code which provided in "velo2cam_projection_detail.ipynb".
Still don't know why, but at least I can get the proper result.
